### ISSUE TITLE
Does not build today - sealed class error

### ISSUE THREAD

**Issue by quicklisp** [GrammaTech/cl-smt-lib#1]
Build log is here: http://report.quicklisp.org/2020-02-24/failure-report/cl-smt-lib.html#cl-smt-lib

It looks to me like this library might be sbcl-only - can you tell me if that is the case?

**Comment by eschulte** [comment]
Confirmed this is an sbcl-only library.  Is there a good way for me to annotate that either programmatically or following some standard?

Thanks

**Comment by quicklisp** [comment]
By policy, I do not include libraries that work only on a single implementation. Is there something SBCL-specific about this library or is it possible it could be ported to more than SBCL?

**Comment by eschulte** [comment]
That makes sense.  I've just pushed up a commit so that this library now works with CCL and SBCL.  In principle it should now work with any library that supports `uiop:launch-program`.  The difference between the `#+ccl` and `#+sbcl` portions are that CCL implements `two-way-stream` as a class (meaning the `smt` object in this library is a normal class) where as SBCL implements `two-way-stream` as a structure (meaning the `smt` object in this library is a structure).  Presumably other lisps could be added to either implementation depending on how they implement `two-way-stream`.

Please let me know if I can do anything else to help.

Thanks!

**Comment by quicklisp** [comment]
On SBCL, you can't subclass `two-way-stream` any more. Are there updates to address that new limitation?

**Comment by eschulte** [comment]
I'm not seeing any errors or warnings with sbcl `2.0.1`.  Should I build the development version of SBCL locally?

**Comment by quicklisp** [comment]
I'm using 2.0.1.149-8fdd882aa when I see the warning in
http://report.quicklisp.org/2020-02-28/failure-report/cl-smt-lib.html#cl-smt-lib

On Fri, Feb 28, 2020 at 1:40 PM Eric Schulte <notifications@github.com>
wrote:
>
> I'm not seeing any errors or warnings with sbcl 2.0.1. Should I build the
development version of SBCL locally?

**Comment by eschulte** [comment]
Okay, it sounds like I should probably wrap two-way-stream using trivial-gray-streams.  I'll try to look into this some time soon, but it may be a couple of weeks.  I'll make a note to update this issue when I do.

Thanks

**Comment by eschulte** [comment]
Okay, I've re-worked this to build off of trivial-gray-streams.  It should now support every lisp implementation that is supported by trivial-gray-streams and it should no longer throw a sealed class error on SBCL.

In addition there are now two new sub-packages providing a two-way-stream built on trivial-gray-streams and for wrapping such a two-way-stream around a process' input and output.

**Comment by eschulte** [comment]
Okay, I'm going to close this issue as I believe it should now be resolved.
